startapp/urls.py
from django.contrib import admin
from django.urls import path,include
from startapp.views import index,detail,cart_view,order,return_view,cancel_view
app_name='startapp'
urlpatterns = [
    path('',index,name='index'),
    path('<int:product_id>/<slug:slug>',detail,name='detail'),
    path('cart/',cart_view,name='cart_view'),
    path('order/',order,name='order'),
    path('success/',return_view,name='return_view'),
    path('cancel/',cancel_view,name='cancel_view'),

]

startproject/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('startapp.urls')),
     path('paypal/', include("paypal.standard.ipn.urls")),
    path('account/',include('registration.backends.default.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

startapp/models.py
from django.db import models

# Create your models here.
class Product(models.Model):
    title=models.CharField(max_length=20)
    description=models.TextField()
    slug=models.SlugField()
    price=models.DecimalField(max_digits=10,decimal_places=2)
    image=models.ImageField(upload_to='')
    def __str__(self):
        return self.title
class Cart(models.Model):
    cart_id=models.CharField(max_length=15)
    price=models.DecimalField(max_digits=10,decimal_places=2)
    quantity=models.IntegerField()
    timestamp= models.DateTimeField(auto_now=True)
    product=models.ForeignKey(Product,on_delete=models.PROTECT)

    def __str__(self):
        return self.product.title
    
    def update_quantity(self,quantity):
        self.quantity+=quantity
        self.save()
    def total(self):
        return self.quantity*self.price   
class Buy(models.Model):
    Product=models.ForeignKey(Product,on_delete=models.PROTECT)
    quantity=models.IntegerField()
    price=models.DecimalField(max_digits=10,decimal_places=2)

    def __str__(self):
        return self.Product.title+'_'+str(self.id)

startapp/forms.py
from collections.abc import Mapping
from typing import Any
from django import forms
from django.forms.utils import ErrorList
class CartForm(forms.Form):
    quantity=forms.IntegerField(initial=1)
    product_id=forms.IntegerField(widget=forms.HiddenInput)

    def __init__(self,request,*args,**kwargs):
        self.request=request
        super(CartForm,self).__init__(*args,**kwargs)
        

startapp/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from startapp.models import Product,Cart,Buy
# Create your views here.
from startapp.forms import CartForm
from startapp.startapp import *

from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin

from django.urls import reverse
from django.shortcuts import render
from paypal.standard.forms import PayPalPaymentsForm


def index(request):
    p=Product.objects.all()
    if request.GET.get('q'):
        query=request.GET.get('q')
        p=Product.objects.filter(title__contains=query)
    context={'p':p}
    return render(request,'index.html',context)
@login_required
def detail(request,product_id,slug):
    d=Product.objects.get(id=product_id)
    if request.method=="POST":
        f=CartForm(request,request.POST)
        if f.is_valid():
            request.form_data=f.cleaned_data
            add_to_cart(request)
            #return HttpResponse('added to cart')
            return redirect('startapp:cart_view')
    f=CartForm(request,initial={'product_id':product_id})
    context={'d':d,'f':f}
    return render(request,'detail.html',context)
@login_required
def cart_view(request):
    if request.method=='POST' and request.POST.get('delete')=='delete':
        item_id=request.POST.get('item_id')
        cd=Cart.objects.get(id=item_id)
        cd.delete()
    c=get_cart(request)
    t=total(request)
    co=item_count(request)
    context={'c':c,'t':t}
    return render(request,'cart.html',context)
@login_required
def order(request):


    # What you want the button to do.
    items=get_cart(request)
    for i in items:
        b=Buy(Product_id=i.product_id,quantity=i.quantity,price=i.price)
        b.save()
    paypal_dict = {
        "business": "sb-6ivrx28145946@business.example.com",
        "amount": total(request),
        "item_name": cart_id(request),
        "invoice": str(
            ()),
        "notify_url": request.build_absolute_uri(reverse('paypal-ipn')),
        "return": request.build_absolute_uri(reverse('startapp:return_view')),
        "cancel_return": request.build_absolute_uri(reverse('startapp:cancel_view')),
        "custom": "premium_plan",  # Custom command to correlate to some function later (optional)
    }

    # Create the instance.
    
    form = PayPalPaymentsForm(initial=paypal_dict)
    context = {"form": form,"items":items,"total":total(request)}
    return render(request, "order.html", context)
@login_required
def return_view(request):
    return HttpResponse('transaction success')
@login_required
def cancel_view(request):
    return HttpResponse('transaction canceled   ....go to school....')

startapp/templates/base.html
<!DOCTYPE html>
<html>
<head>
	<title>ecommerce</title>
	<!-- CSS only -->
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

	<!-- JS, Popper.js, and jQuery -->
	<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
	<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
  <script src="https://kit.fontawesome.com/411101df7a.js" crossorigin="anonymous"></script>
</head>
<style>

  body{
    background-color: rgb(164, 233, 183);
  }
  
</style>
<body>
	<nav class="navbar navbar-dark bg-dark" style="background-color: #4388ba;">
  <a class="navbar-brand" href="#">Ecommerce</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Post</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#"></a>
      </li>
    </ul>


    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" name="q" value="{{request.GET.q}}" placeholder="search" aria-label="Search">
      <a href="{% url 'startapp:cart_view' %}" class="btn btn-outline-success my-2 my-sm-0" >Cart</a>
    </form>&nbsp;
  
    <a class="btn btn-primary" href="{% url 'auth_login' %}">Login</a>&nbsp;
    <a class="btn btn-primary" href="{% url 'registration_register' %}">Register</a>

    <a class="btn btn-primary" href="{% url 'auth_logout' %}">Logout</a>
    
  

  </div>
</nav>

{% block content %}
{% endblock %}
</body>
</html>

startapp/templates/cancel_view.html
{% extends 'base.html' %}
{% block content %}
<style>
    body{
        background-color: tomato;
    }
    h3{
        content: center;
    }
</style>
<body>
    <h3>canceled</h3>
</body>
{% endblock %}

startapp/templates/cart.html
{% extends 'base.html'%}
{% block content %}
<table class="table table-striped table-dark">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Product</th>
        <th scope="col">Price</th>
        <th scope="col">Quantity</th>
        <th scope="col">Total cost</th>
      </tr>
    </thead>
    <tbody>
        {% for i in c %}
      <tr>
        <th scope="row">{{forloop.counter}}</th>
        <td>{{i.product}}</td>
        <td>{{i.price}}</td>
        <td>{{i.quantity}}</td>
        <td>{{i.total}}</td>
       <td>
         <form action="" method="POST">
            {% csrf_token %}
            <input type="hidden" name="item_id" value="{{i.id}}">
            <input class="btn btn-outline-danger" type="submit" name="delete" value="delete">
        </form>
    </td>
      </tr>
     {% endfor %}
    </tbody>
  </table>
<center><h4 class="btn-outline-success"><br>Total:{{t}}<br></h4></center>
<a href="{% url 'startapp:index' %}"><h6 class="btn btn-outline-danger">back</h6></a>
&nbsp;&nbsp;&nbsp;
 <center><br><a href="{% url 'startapp:order' %}" class="btn btn-light">  ORDER  </a><br></center>
{% endblock %}

startapp/templates/detail.html
{% extends 'base.html' %}
{% block content %}
<div class="row">
    <div class="col-md-6">
        {{d.title}} <br>
        {{d.description}} <br>
        {{d.price}}
    </div>
    <div class="col-md-6">
        <img src="{{d.image.url}}" >
    <br><br>
    </div>
</div>
<form action="{% url 'startapp:detail' d.id d.slug %}" method="post">
    {% csrf_token %}
    {{ f }}
    <input class="btn btn-outline-primary" type="submit" value="Add to cart">
</form>
{% endblock %}

startapp/templates/index.html
{% extends 'base.html' %}
{% block content %}
<div class="row">
    {% for i in p %}
    
    <div class="col-md-6">
      <a href="{% url 'startapp:detail' i.id i.slug %}"> <b> {{i.title}} </b> <br></a>
        <img src="{{i.image.url}}" width=400 height=500 alt=""> <br><br>
       Rs{{i.price}} <br>
    <br>;
    </div>




    
    {% endfor %}
</div>
{% endblock %}

startapp/templates/order.html
{% extends 'base.html' %}
{% block content %}
<center>
<b>Cart</b><br>
<h5>Products:</h5>
{% for i in items %}
{{i.product}}<br>
{% endfor %}
<h5>Total Amount to pay: </h5>{{total}}
<font class="" style="font-family: Impact, Haettenschweiler, 'Arial Narrow Bold', sans-serif;">Show me the money!</font>
<!-- writes out the form tag automatically -->
{{ form.render }}
</center>
{% endblock %}

startapp/templates/return_view.html
{% extends 'base.html' %}
{% block content %}
{% endblock %}